apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-price 
  template:
    metadata:
      labels:
        app: flight-price 
    spec:
      containers:
      - name: flight-price-container 
        image: flight-price-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000